import { type Program } from "./types";

export const programs: Program[] = [
  // ═══════════════════════════════════════════════════
  // FOOD & NUTRITION
  // ═══════════════════════════════════════════════════
  {
    slug: "snap",
    name: "SNAP",
    full_name: "Supplemental Nutrition Assistance Program",
    category: "food",
    summary: "Monthly food assistance for low-income individuals and families across the US",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1580, net_monthly: 1215 },
        { household_size: 2, gross_monthly: 2137, net_monthly: 1644 },
        { household_size: 3, gross_monthly: 2694, net_monthly: 2072 },
        { household_size: 4, gross_monthly: 3250, net_monthly: 2500 },
        { household_size: 5, gross_monthly: 3807, net_monthly: 2929 },
        { household_size: 6, gross_monthly: 4364, net_monthly: 3357 },
        { household_size: 7, gross_monthly: 4921, net_monthly: 3785 },
        { household_size: 8, gross_monthly: 5478, net_monthly: 4214 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Most states have broad categorical eligibility for households receiving TANF or SSI",
        "Able-bodied adults without dependents (18-49) must work 20+ hours/week",
        "Some legal immigrants qualify after 5 years of residency",
        "Students enrolled in college half-time or more generally do not qualify unless they meet an exemption",
      ],
    },
    benefit: {
      type: "Monthly EBT card",
      average_amount: "$187/person/month",
      duration: "Ongoing (renew every 12 months)",
    },
    application: {
      apply_url: "https://www.benefits.gov/benefit/361",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "30 days",
      expedited_available: true,
      expedited_timeline: "7 days for very low income",
    },
    documents_needed: [
      "State-issued photo ID or driver's license",
      "Social Security numbers for all household members",
      "Proof of income (pay stubs, unemployment letter, SSI letter)",
      "Proof of residency (utility bill, lease agreement)",
      "Rent/mortgage payment documentation",
      "Utility bills",
      "Birth certificates for children",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your state's application portal",
        description: "SNAP is administered by each state. You must apply through your state's benefits portal, not the federal website.",
        time_estimate: "2 minutes",
        action_url: "https://www.benefits.gov/benefit/361",
        action_label: "Find My State Portal →",
      },
      {
        step_number: 2,
        title: "Gather your documents before you start",
        description: "Having everything ready before you start prevents delays. You don't need originals — most states accept photos or scans.",
        time_estimate: "15-20 minutes to gather",
      },
      {
        step_number: 3,
        title: "Complete the application",
        description: "The online application takes 30-60 minutes. You can save and return. You'll be asked about everyone in your household, income, housing costs, utility costs, and other benefits you receive.",
        tips: [
          "Apply even if you're not sure you qualify. The agency will determine eligibility.",
          "If your income changes soon, you may qualify even if you're borderline today.",
        ],
        time_estimate: "30-60 minutes",
      },
      {
        step_number: 4,
        title: "Attend your interview",
        description: "Most states require a brief interview — usually by phone. They'll call you within 1-2 weeks of applying. The interview typically takes 15-30 minutes.",
        tips: [
          "If you miss the call, call back immediately. Missing the interview can delay or deny your application.",
        ],
        time_estimate: "15-30 minute phone call",
      },
      {
        step_number: 5,
        title: "Receive your decision",
        description: "You'll receive a written notice within 30 days of applying. If approved, you'll get an EBT card in the mail within 7-10 days.",
        time_estimate: "Up to 30 days",
      },
      {
        step_number: 6,
        title: "Maintain your benefits",
        description: "SNAP benefits are not permanent. You must report income changes within 10 days and renew every 12 months (6 months for some households).",
        time_estimate: "Ongoing",
      },
    ],
    faqs: [
      { question: "Can I apply if I'm undocumented?", answer: "SNAP requires citizenship or qualifying immigration status. However, your children who are US citizens may qualify even if you don't." },
      { question: "What if I already have a job?", answer: "Yes. Many working families qualify for SNAP. The income limits are higher than most people realize." },
      { question: "Does applying affect my immigration case?", answer: "Since 2023, using SNAP generally does not affect green card applications (public charge rule). Consult an immigration lawyer for your specific situation." },
      { question: "Can I use SNAP at farmers markets?", answer: "Yes. Most farmers markets that accept EBT are listed at usda.gov/FMD." },
      { question: "What if my income changes after I apply?", answer: "Report significant changes within 10 days. If your income drops, you may qualify for higher benefits." },
      { question: "Can I get SNAP and other programs at the same time?", answer: "Yes. SNAP can be combined with Medicaid, housing assistance, TANF, WIC, and most other programs." },
    ],
    can_combine_with: ["medicaid", "tanf", "wic", "liheap", "section-8"],
    source_url: "https://www.fns.usda.gov/snap",
    last_updated: "2024-10",
  },

  {
    slug: "wic",
    name: "WIC",
    full_name: "Women, Infants, and Children",
    category: "food",
    summary: "Nutrition assistance for pregnant women, new mothers, infants, and children under 5",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 2248, net_monthly: 2248 },
        { household_size: 2, gross_monthly: 3041, net_monthly: 3041 },
        { household_size: 3, gross_monthly: 3833, net_monthly: 3833 },
        { household_size: 4, gross_monthly: 4625, net_monthly: 4625 },
        { household_size: 5, gross_monthly: 5418, net_monthly: 5418 },
        { household_size: 6, gross_monthly: 6210, net_monthly: 6210 },
      ],
      citizenship_required: false,
      age_range: { max: 5 },
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For pregnant women, new mothers (up to 1 year postpartum), infants, and children under 5",
        "Income at or below 185% of Federal Poverty Level",
        "Immigration status does not affect eligibility",
        "Auto-qualify if receiving SNAP, Medicaid, or TANF",
      ],
    },
    benefit: {
      type: "Monthly food package (EBT card or vouchers)",
      average_amount: "$50-75/month in approved foods",
      duration: "Until child turns 5 or mother is 1 year postpartum",
    },
    application: {
      apply_url: "https://www.fns.usda.gov/wic",
      apply_phone: "1-800-311-3257",
      can_apply_online: false,
      requires_interview: true,
      decision_timeline: "Same day at appointment",
      expedited_available: false,
    },
    documents_needed: [
      "Proof of identity (ID, driver's license)",
      "Proof of residency (utility bill, mail)",
      "Proof of income (pay stubs, tax return)",
      "Proof of pregnancy or child's age (medical records, birth certificate)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your local WIC office",
        description: "WIC operates through local clinics. Find yours by calling 1-800-311-3257 or searching online for '[your state] WIC office.'",
        time_estimate: "5 minutes",
        action_url: "https://www.fns.usda.gov/wic/wic-how-apply",
        action_label: "Find WIC Office →",
      },
      {
        step_number: 2,
        title: "Schedule an appointment",
        description: "Call your local WIC office to schedule an appointment. Some offices allow walk-ins.",
        time_estimate: "5 minutes",
      },
      {
        step_number: 3,
        title: "Attend your appointment",
        description: "Bring your documents. A nutritionist will assess your needs and determine eligibility on the spot. You'll receive your benefits the same day if approved.",
        time_estimate: "30-60 minutes",
      },
      {
        step_number: 4,
        title: "Receive your benefits",
        description: "You'll get a WIC EBT card or vouchers for specific approved foods (milk, eggs, cereal, fruits, vegetables, etc.).",
        time_estimate: "Same day",
      },
    ],
    faqs: [
      { question: "Do I need to be a US citizen?", answer: "No. WIC does not require citizenship or legal immigration status. It is available to all eligible residents." },
      { question: "I'm pregnant — when should I apply?", answer: "Apply as soon as you know you're pregnant. WIC provides prenatal nutrition support." },
      { question: "What foods can I buy with WIC?", answer: "WIC provides specific foods: milk, cheese, eggs, cereal, juice, fruits, vegetables, peanut butter, beans, and infant formula." },
    ],
    can_combine_with: ["snap", "medicaid", "tanf", "chip"],
    source_url: "https://www.fns.usda.gov/wic",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // HEALTHCARE
  // ═══════════════════════════════════════════════════
  {
    slug: "medicaid",
    name: "Medicaid",
    full_name: "Medicaid Health Insurance",
    category: "health",
    summary: "Free or low-cost health insurance for low-income adults, children, pregnant women, and people with disabilities",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1732, net_monthly: 1732 },
        { household_size: 2, gross_monthly: 2342, net_monthly: 2342 },
        { household_size: 3, gross_monthly: 2952, net_monthly: 2952 },
        { household_size: 4, gross_monthly: 3562, net_monthly: 3562 },
        { household_size: 5, gross_monthly: 4172, net_monthly: 4172 },
        { household_size: 6, gross_monthly: 4782, net_monthly: 4782 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Adults up to 138% FPL in Medicaid expansion states (41 states + DC)",
        "Children generally qualify at higher income levels (up to 200-300% FPL)",
        "Pregnant women qualify at higher levels in most states",
        "Some states have not expanded Medicaid — check your state",
        "Legal immigrants may qualify after 5-year waiting period",
      ],
    },
    benefit: {
      type: "Health insurance coverage",
      average_amount: "Free or very low cost ($0-$10 copays)",
      duration: "Ongoing while eligible (renew annually)",
    },
    application: {
      apply_url: "https://www.healthcare.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "45 days (90 days for disability-based)",
      expedited_available: false,
    },
    documents_needed: [
      "Social Security numbers for all applicants",
      "Proof of citizenship or immigration status",
      "Proof of income",
      "Proof of residency",
      "Information about current health coverage",
    ],
    steps: [
      {
        step_number: 1,
        title: "Check if your state expanded Medicaid",
        description: "Most states expanded Medicaid under the ACA, but some have not. This affects income eligibility for adults.",
        time_estimate: "2 minutes",
        action_url: "https://www.healthcare.gov/medicaid-chip/",
        action_label: "Check My State →",
      },
      {
        step_number: 2,
        title: "Apply online or by phone",
        description: "Apply through Healthcare.gov or your state Medicaid office. You can also apply by phone or in person.",
        time_estimate: "20-30 minutes",
        action_url: "https://www.healthcare.gov/",
        action_label: "Apply on Healthcare.gov →",
      },
      {
        step_number: 3,
        title: "Provide documentation",
        description: "Submit income verification and identity documents. Many states can verify electronically.",
        time_estimate: "10-15 minutes",
      },
      {
        step_number: 4,
        title: "Receive your decision",
        description: "Most applications are decided within 45 days. If approved, you'll receive a Medicaid card and can begin using benefits.",
        time_estimate: "Up to 45 days",
      },
    ],
    faqs: [
      { question: "Can I have Medicaid and a job?", answer: "Yes. Many working people qualify for Medicaid, especially in expansion states." },
      { question: "Does Medicaid cover dental and vision?", answer: "It depends on your state. Most states cover these for children. Adult dental/vision coverage varies." },
      { question: "What if I make too much for Medicaid?", answer: "You may qualify for subsidized ACA marketplace insurance through Healthcare.gov." },
    ],
    can_combine_with: ["snap", "tanf", "wic", "liheap", "section-8"],
    source_url: "https://www.medicaid.gov/",
    last_updated: "2024-10",
  },

  {
    slug: "chip",
    name: "CHIP",
    full_name: "Children's Health Insurance Program",
    category: "health",
    summary: "Health insurance for children in families who earn too much for Medicaid but can't afford private insurance",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 2, gross_monthly: 3400, net_monthly: 3400 },
        { household_size: 3, gross_monthly: 4284, net_monthly: 4284 },
        { household_size: 4, gross_monthly: 5167, net_monthly: 5167 },
        { household_size: 5, gross_monthly: 6050, net_monthly: 6050 },
      ],
      citizenship_required: true,
      age_range: { max: 19 },
      requires_children: true,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For children under 19",
        "Income limits vary by state (generally 200-300% FPL)",
        "Some states also cover pregnant women through CHIP",
      ],
    },
    benefit: {
      type: "Health insurance for children",
      average_amount: "Free or low-cost premiums ($0-$50/month)",
      duration: "Until age 19 or income changes",
    },
    application: {
      apply_url: "https://www.insurekidsnow.gov/",
      apply_phone: "1-877-543-7669",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "30-45 days",
      expedited_available: false,
    },
    documents_needed: [
      "Child's Social Security number",
      "Proof of child's age (birth certificate)",
      "Proof of household income",
      "Proof of residency",
    ],
    steps: [
      {
        step_number: 1,
        title: "Apply through Insure Kids Now",
        description: "Call 1-877-543-7669 or apply online through your state's Medicaid/CHIP portal.",
        time_estimate: "15-20 minutes",
        action_url: "https://www.insurekidsnow.gov/",
        action_label: "Apply Now →",
      },
      {
        step_number: 2,
        title: "Submit documents",
        description: "Provide income and identity verification for your household.",
        time_estimate: "10 minutes",
      },
      {
        step_number: 3,
        title: "Receive coverage",
        description: "Once approved, your child receives a health insurance card and can see doctors, specialists, and get prescriptions.",
        time_estimate: "2-4 weeks",
      },
    ],
    faqs: [
      { question: "What's the difference between Medicaid and CHIP?", answer: "CHIP is for families who earn too much for Medicaid but still need affordable coverage for their children." },
      { question: "Does CHIP cover dental?", answer: "Yes. CHIP covers dental, vision, and mental health services for children in all states." },
    ],
    can_combine_with: ["snap", "wic", "tanf"],
    source_url: "https://www.insurekidsnow.gov/",
    last_updated: "2024-10",
  },

  {
    slug: "aca-marketplace",
    name: "ACA Marketplace",
    full_name: "Affordable Care Act Health Insurance Marketplace",
    category: "health",
    summary: "Subsidized health insurance for individuals and families who don't qualify for Medicaid",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 4838, net_monthly: 4838 },
        { household_size: 2, gross_monthly: 6538, net_monthly: 6538 },
        { household_size: 3, gross_monthly: 8238, net_monthly: 8238 },
        { household_size: 4, gross_monthly: 9938, net_monthly: 9938 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Subsidies available for income between 100-400% FPL",
        "Enhanced subsidies extended through 2025",
        "Open enrollment typically November-January",
        "Special enrollment if you lose coverage, move, or have a life change",
      ],
    },
    benefit: {
      type: "Subsidized health insurance premiums",
      average_amount: "Subsidies average $500+/month off premiums",
      duration: "Annual (renew during open enrollment)",
    },
    application: {
      apply_url: "https://www.healthcare.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "Immediate eligibility determination",
      expedited_available: false,
    },
    documents_needed: [
      "Social Security numbers for all household members",
      "Income information (pay stubs, tax return)",
      "Current health coverage details",
    ],
    steps: [
      {
        step_number: 1,
        title: "Visit Healthcare.gov",
        description: "Create an account and start your application during open enrollment or a special enrollment period.",
        time_estimate: "10 minutes",
        action_url: "https://www.healthcare.gov/",
        action_label: "Start Application →",
      },
      {
        step_number: 2,
        title: "Enter your household information",
        description: "Provide details about your household size, income, and current coverage.",
        time_estimate: "15-20 minutes",
      },
      {
        step_number: 3,
        title: "Compare plans and enroll",
        description: "Review available plans, see your subsidy amount, and select the plan that works for you.",
        time_estimate: "20-30 minutes",
      },
    ],
    faqs: [
      { question: "When is open enrollment?", answer: "Open enrollment is typically November 1 through January 15. You can also enroll during special enrollment periods triggered by life events." },
      { question: "Can I apply if I have employer insurance?", answer: "You can, but you typically won't receive subsidies unless your employer coverage is unaffordable (costs more than ~8% of income)." },
    ],
    can_combine_with: ["snap", "liheap"],
    source_url: "https://www.healthcare.gov/",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // HOUSING
  // ═══════════════════════════════════════════════════
  {
    slug: "section-8",
    name: "Section 8",
    full_name: "Housing Choice Voucher Program (Section 8)",
    category: "housing",
    summary: "Rental assistance vouchers that help low-income families afford private housing",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 2500, net_monthly: 2500 },
        { household_size: 2, gross_monthly: 2858, net_monthly: 2858 },
        { household_size: 3, gross_monthly: 3215, net_monthly: 3215 },
        { household_size: 4, gross_monthly: 3571, net_monthly: 3571 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income must be below 50% of Area Median Income (AMI) for your county",
        "Waitlists are often very long (1-5+ years)",
        "Priority given to extremely low-income, elderly, and disabled",
        "Must be a US citizen or eligible immigrant",
      ],
    },
    benefit: {
      type: "Monthly rental voucher",
      average_amount: "Covers ~70% of rent (you pay ~30% of income)",
      duration: "Ongoing while eligible",
    },
    application: {
      apply_url: "https://www.hud.gov/program_offices/public_indian_housing",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "Varies (waitlists common)",
      expedited_available: false,
    },
    documents_needed: [
      "Government-issued photo ID",
      "Social Security cards for all household members",
      "Birth certificates",
      "Proof of income (pay stubs, benefit letters)",
      "Proof of current address",
      "Previous landlord references",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your local Public Housing Authority (PHA)",
        description: "Section 8 is managed by local housing authorities. Find yours at hud.gov.",
        time_estimate: "5 minutes",
        action_url: "https://www.hud.gov/program_offices/public_indian_housing/pha/contacts",
        action_label: "Find My PHA →",
      },
      {
        step_number: 2,
        title: "Apply when the waitlist opens",
        description: "Most PHAs open their waitlist periodically. You must apply during that window.",
        time_estimate: "30-45 minutes",
      },
      {
        step_number: 3,
        title: "Wait for your name to be called",
        description: "Waitlists can be 1-5+ years. Keep your contact info updated with the PHA.",
        time_estimate: "Months to years",
      },
      {
        step_number: 4,
        title: "Find an approved unit",
        description: "Once selected, you have a limited time to find a landlord who accepts Section 8 vouchers.",
        time_estimate: "60-120 days",
      },
    ],
    faqs: [
      { question: "How long is the waitlist?", answer: "Waitlists vary widely. Some areas have 1-2 year waits, others 5+ years. Apply early and to multiple PHAs if possible." },
      { question: "Can I choose where to live?", answer: "Yes. You can use your voucher at any rental property where the landlord accepts Section 8." },
    ],
    can_combine_with: ["snap", "medicaid", "liheap", "tanf"],
    source_url: "https://www.hud.gov/topics/housing_choice_voucher_program_section_8",
    last_updated: "2024-10",
  },

  {
    slug: "emergency-rental-assistance",
    name: "ERA",
    full_name: "Emergency Rental Assistance Program",
    category: "housing",
    summary: "Emergency help for renters behind on rent or at risk of eviction",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 3325, net_monthly: 3325 },
        { household_size: 2, gross_monthly: 3800, net_monthly: 3800 },
        { household_size: 3, gross_monthly: 4275, net_monthly: 4275 },
        { household_size: 4, gross_monthly: 4750, net_monthly: 4750 },
      ],
      citizenship_required: false,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income below 80% of Area Median Income",
        "Must demonstrate financial hardship or risk of homelessness",
        "Availability varies by state and locality — funds may be exhausted",
        "Can cover past-due rent, future rent, and utility bills",
      ],
    },
    benefit: {
      type: "Direct rent/utility payments",
      average_amount: "Up to 12-18 months of rent and utilities",
      duration: "One-time (up to 18 months)",
    },
    application: {
      apply_url: "https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/emergency-rental-assistance-program",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "2-6 weeks",
      expedited_available: true,
      expedited_timeline: "Priority for those with eviction notices",
    },
    documents_needed: [
      "Photo ID",
      "Lease agreement",
      "Proof of income loss or financial hardship",
      "Past-due rent notice or eviction filing",
      "Landlord contact information",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your local ERA program",
        description: "Emergency rental assistance is distributed through state and local programs. Search for your area's program.",
        time_estimate: "5 minutes",
        action_url: "https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/emergency-rental-assistance-program",
        action_label: "Find My Program →",
      },
      {
        step_number: 2,
        title: "Apply online",
        description: "Submit your application with proof of hardship, income, and lease information.",
        time_estimate: "30-45 minutes",
      },
      {
        step_number: 3,
        title: "Receive assistance",
        description: "If approved, funds are paid directly to your landlord and/or utility provider.",
        time_estimate: "2-6 weeks",
      },
    ],
    faqs: [
      { question: "Do I need my landlord's cooperation?", answer: "Ideally yes, but some programs can provide funds directly to you if the landlord won't participate." },
      { question: "Is this program still active?", answer: "Availability varies. Some states have exhausted federal funds but offer state-funded alternatives." },
    ],
    can_combine_with: ["snap", "medicaid", "liheap"],
    source_url: "https://home.treasury.gov/policy-issues/coronavirus/assistance-for-state-local-and-tribal-governments/emergency-rental-assistance-program",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // CHILD & FAMILY
  // ═══════════════════════════════════════════════════
  {
    slug: "tanf",
    name: "TANF",
    full_name: "Temporary Assistance for Needy Families",
    category: "family",
    summary: "Cash assistance for families with children experiencing financial hardship",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 2, gross_monthly: 1200, net_monthly: 1200 },
        { household_size: 3, gross_monthly: 1500, net_monthly: 1500 },
        { household_size: 4, gross_monthly: 1800, net_monthly: 1800 },
        { household_size: 5, gross_monthly: 2100, net_monthly: 2100 },
      ],
      citizenship_required: true,
      requires_children: true,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Must have a child under 18 or be pregnant",
        "Income limits vary significantly by state (above are rough averages)",
        "Time-limited: 60-month lifetime limit in most states",
        "Work requirements for most adult recipients",
      ],
    },
    benefit: {
      type: "Monthly cash payment",
      average_amount: "$300-700/month (varies by state and household size)",
      duration: "Up to 60 months (5 years) lifetime",
    },
    application: {
      apply_url: "https://www.benefits.gov/benefit/613",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "30-45 days",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID",
      "Social Security numbers for all family members",
      "Birth certificates for children",
      "Proof of income",
      "Proof of residency",
      "Proof of pregnancy (if applicable)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your state's TANF program",
        description: "TANF is known by different names in different states (CalWORKs in CA, TAFDC in MA, etc.).",
        time_estimate: "5 minutes",
        action_url: "https://www.benefits.gov/benefit/613",
        action_label: "Find My State Program →",
      },
      {
        step_number: 2,
        title: "Complete the application",
        description: "Apply online, by phone, or in person at your local social services office.",
        time_estimate: "30-45 minutes",
      },
      {
        step_number: 3,
        title: "Attend your eligibility interview",
        description: "You'll meet with a caseworker to review your application and discuss work requirements.",
        time_estimate: "30-60 minutes",
      },
      {
        step_number: 4,
        title: "Begin receiving benefits",
        description: "If approved, you'll receive monthly cash assistance via direct deposit or EBT card.",
        time_estimate: "2-4 weeks after approval",
      },
    ],
    faqs: [
      { question: "Do I have to work to receive TANF?", answer: "Most states require work or work-related activities (job training, education). Exemptions exist for caregivers of very young children, people with disabilities, etc." },
      { question: "Is there a lifetime limit?", answer: "Most states enforce a 60-month (5-year) lifetime limit on TANF benefits, though some states have shorter limits." },
    ],
    can_combine_with: ["snap", "medicaid", "wic", "section-8", "liheap", "ccap-childcare"],
    source_url: "https://www.acf.hhs.gov/ofa/tanf",
    last_updated: "2024-10",
  },

  {
    slug: "ccap-childcare",
    name: "CCAP",
    full_name: "Child Care Assistance Program",
    category: "family",
    summary: "Subsidized childcare for low-income working families",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 2, gross_monthly: 3400, net_monthly: 3400 },
        { household_size: 3, gross_monthly: 4284, net_monthly: 4284 },
        { household_size: 4, gross_monthly: 5167, net_monthly: 5167 },
        { household_size: 5, gross_monthly: 6050, net_monthly: 6050 },
      ],
      citizenship_required: true,
      requires_children: true,
      requires_disability: false,
      requires_employment_history: true,
      special_notes: [
        "Must be working, in job training, or in school",
        "Children must be under 13 (or under 19 with special needs)",
        "Income limits vary by state (generally up to 85% SMI)",
        "Waitlists common in many states",
      ],
    },
    benefit: {
      type: "Childcare subsidy (copay reduction)",
      average_amount: "Covers 60-90% of childcare costs",
      duration: "While working/training and income-eligible",
    },
    application: {
      apply_url: "https://www.childcare.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "2-4 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Proof of employment or school enrollment",
      "Proof of income",
      "Children's birth certificates",
      "Photo ID",
      "Chosen childcare provider's information",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your state's childcare assistance program",
        description: "Each state administers childcare subsidies differently. Find your program at childcare.gov.",
        time_estimate: "5 minutes",
        action_url: "https://www.childcare.gov/",
        action_label: "Find My State Program →",
      },
      {
        step_number: 2,
        title: "Apply and provide documentation",
        description: "Submit proof of work/school, income, and children's ages.",
        time_estimate: "20-30 minutes",
      },
      {
        step_number: 3,
        title: "Choose a childcare provider",
        description: "Select a licensed provider (daycare, family home, etc.). The subsidy pays the provider directly.",
        time_estimate: "Variable",
      },
    ],
    faqs: [
      { question: "Can I use this for any childcare provider?", answer: "The provider must be licensed or meet your state's requirements. Family members may qualify in some states." },
    ],
    can_combine_with: ["snap", "medicaid", "tanf", "wic"],
    source_url: "https://www.childcare.gov/",
    last_updated: "2024-10",
  },

  {
    slug: "head-start",
    name: "Head Start",
    full_name: "Head Start / Early Head Start",
    category: "education",
    summary: "Free early childhood education and family support for low-income families with children under 5",
    federal_or_state: "federal",
    eligibility: {
      income_limits: [
        { household_size: 2, gross_monthly: 1702, net_monthly: 1702 },
        { household_size: 3, gross_monthly: 2144, net_monthly: 2144 },
        { household_size: 4, gross_monthly: 2587, net_monthly: 2587 },
      ],
      citizenship_required: false,
      age_range: { max: 5 },
      requires_children: true,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For children birth to age 5",
        "Income at or below 100% FPL",
        "Children in foster care, experiencing homelessness, or from families receiving TANF/SSI auto-qualify",
        "Also serves pregnant women",
      ],
    },
    benefit: {
      type: "Free preschool education + family services",
      average_amount: "Free (full-day or half-day programs)",
      duration: "Until child enters kindergarten",
    },
    application: {
      apply_url: "https://www.acf.hhs.gov/ohs",
      can_apply_online: false,
      requires_interview: true,
      decision_timeline: "Varies by program",
      expedited_available: false,
    },
    documents_needed: [
      "Child's birth certificate",
      "Proof of income",
      "Immunization records",
      "Proof of residency",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find a Head Start program near you",
        description: "Use the Head Start locator to find programs in your area.",
        time_estimate: "5 minutes",
        action_url: "https://eclkc.ohs.acf.hhs.gov/center-locator",
        action_label: "Find Programs Near Me →",
      },
      {
        step_number: 2,
        title: "Contact the program and apply",
        description: "Call or visit the program to complete an application.",
        time_estimate: "30 minutes",
      },
      {
        step_number: 3,
        title: "Enroll your child",
        description: "If accepted, your child receives free education, meals, health screenings, and family support services.",
        time_estimate: "1-4 weeks",
      },
    ],
    faqs: [
      { question: "Is Head Start only for low-income families?", answer: "Primarily yes, but 10% of enrollment spots can go to families above income limits, and children with disabilities qualify regardless of income." },
    ],
    can_combine_with: ["snap", "medicaid", "wic", "tanf"],
    source_url: "https://www.acf.hhs.gov/ohs",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // UNEMPLOYMENT & JOBS
  // ═══════════════════════════════════════════════════
  {
    slug: "unemployment-insurance",
    name: "Unemployment Insurance",
    full_name: "State Unemployment Insurance",
    category: "unemployment",
    summary: "Weekly cash payments for workers who lost their job through no fault of their own",
    federal_or_state: "state",
    eligibility: {
      income_limits: [],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: true,
      special_notes: [
        "Must have lost job through no fault of your own (not fired for cause)",
        "Must have worked enough hours/weeks in 'base period' (usually last 12-18 months)",
        "Must be actively seeking work",
        "Must be able and available to work",
        "Self-employed workers generally do not qualify",
      ],
    },
    benefit: {
      type: "Weekly cash payment",
      average_amount: "$300-500/week (varies by state and previous earnings)",
      duration: "Up to 26 weeks (6 months) in most states",
    },
    application: {
      apply_url: "https://www.careeronestop.org/LocalHelp/UnemploymentBenefits/find-unemployment-benefits.aspx",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "2-3 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Social Security number",
      "Driver's license or photo ID",
      "Employment history (last 18 months)",
      "Employer names, addresses, and dates of employment",
      "Reason for separation from each employer",
      "Bank account info for direct deposit",
    ],
    steps: [
      {
        step_number: 1,
        title: "File your claim immediately",
        description: "Apply as soon as you lose your job. Benefits don't start until you file. Apply through your state unemployment office.",
        time_estimate: "30-45 minutes",
        action_url: "https://www.careeronestop.org/LocalHelp/UnemploymentBenefits/find-unemployment-benefits.aspx",
        action_label: "Find My State UI Office →",
      },
      {
        step_number: 2,
        title: "Certify weekly/biweekly",
        description: "You must certify that you're still unemployed and actively seeking work each week or every two weeks.",
        time_estimate: "5-10 minutes per week",
      },
      {
        step_number: 3,
        title: "Conduct job searches",
        description: "Most states require you to apply for a certain number of jobs each week and keep records.",
        time_estimate: "Ongoing",
      },
    ],
    faqs: [
      { question: "Can I get unemployment if I was fired?", answer: "Generally no, if you were fired for misconduct. But if laid off, downsized, or fired without cause, you likely qualify." },
      { question: "How much will I receive?", answer: "Benefits are typically about 50% of your previous weekly wages, up to a state maximum." },
    ],
    can_combine_with: ["snap", "medicaid", "liheap"],
    source_url: "https://www.dol.gov/general/topic/unemployment-insurance",
    last_updated: "2024-10",
  },

  {
    slug: "wioa-job-training",
    name: "WIOA",
    full_name: "Workforce Innovation and Opportunity Act Job Training",
    category: "unemployment",
    summary: "Free job training, education, and career services for adults and displaced workers",
    federal_or_state: "both",
    eligibility: {
      income_limits: [],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Available to adults 18+ who are unemployed or underemployed",
        "Priority for low-income individuals, veterans, and people with barriers to employment",
        "No strict income limit for basic career services",
        "Individual Training Accounts (ITAs) may have income requirements",
      ],
    },
    benefit: {
      type: "Free job training + career services",
      average_amount: "Training vouchers up to $5,000-10,000",
      duration: "Varies by training program",
    },
    application: {
      apply_url: "https://www.careeronestop.org/",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "2-4 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID",
      "Social Security card",
      "Proof of residency",
      "Proof of income (if seeking training funds)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Visit your local American Job Center",
        description: "Find your nearest AJC at careeronestop.org. These centers provide free career services.",
        time_estimate: "5 minutes to locate",
        action_url: "https://www.careeronestop.org/LocalHelp/AmericanJobCenters/find-american-job-centers.aspx",
        action_label: "Find a Job Center →",
      },
      {
        step_number: 2,
        title: "Meet with a career counselor",
        description: "Discuss your career goals and options for training, education, or direct job placement.",
        time_estimate: "1 hour",
      },
      {
        step_number: 3,
        title: "Enroll in training",
        description: "If eligible for training funds, choose an approved program and begin your coursework.",
        time_estimate: "Weeks to months",
      },
    ],
    faqs: [
      { question: "Is WIOA only for unemployed people?", answer: "No. WIOA also serves underemployed workers and those seeking career advancement." },
    ],
    can_combine_with: ["snap", "unemployment-insurance", "pell-grant"],
    source_url: "https://www.dol.gov/agencies/eta/wioa",
    last_updated: "2024-10",
  },

  {
    slug: "job-corps",
    name: "Job Corps",
    full_name: "Job Corps",
    category: "unemployment",
    summary: "Free residential job training program for young adults ages 16-24",
    federal_or_state: "federal",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1215, net_monthly: 1215 },
        { household_size: 2, gross_monthly: 1644, net_monthly: 1644 },
        { household_size: 3, gross_monthly: 2072, net_monthly: 2072 },
      ],
      citizenship_required: true,
      age_range: { min: 16, max: 24 },
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For young adults ages 16-24",
        "Low-income requirement (generally 100% FPL)",
        "Provides housing, meals, healthcare, and job training at no cost",
        "Over 120 centers across the US",
      ],
    },
    benefit: {
      type: "Free education, training, housing, and meals",
      average_amount: "Full room and board + living allowance + training",
      duration: "Up to 2 years",
    },
    application: {
      apply_url: "https://www.jobcorps.gov/",
      apply_phone: "1-800-733-5627",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "2-4 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID",
      "Birth certificate",
      "Social Security card",
      "Proof of income",
    ],
    steps: [
      {
        step_number: 1,
        title: "Apply online or call",
        description: "Visit jobcorps.gov or call 1-800-733-5627 to start your application.",
        time_estimate: "15 minutes",
        action_url: "https://www.jobcorps.gov/recruiting",
        action_label: "Apply Now →",
      },
      {
        step_number: 2,
        title: "Meet with an admissions counselor",
        description: "You'll meet with a counselor to discuss program options and career interests.",
        time_estimate: "1 hour",
      },
      {
        step_number: 3,
        title: "Enroll and begin training",
        description: "Move to a Job Corps center and begin your education/training program.",
        time_estimate: "2-4 weeks after acceptance",
      },
    ],
    faqs: [
      { question: "Is Job Corps really free?", answer: "Yes. Job Corps covers housing, meals, basic healthcare, and all training costs. You also receive a living allowance." },
    ],
    can_combine_with: ["snap", "medicaid"],
    source_url: "https://www.jobcorps.gov/",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // UTILITIES & BILLS
  // ═══════════════════════════════════════════════════
  {
    slug: "liheap",
    name: "LIHEAP",
    full_name: "Low Income Home Energy Assistance Program",
    category: "utilities",
    summary: "Help paying heating and cooling bills for low-income households",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1823, net_monthly: 1823 },
        { household_size: 2, gross_monthly: 2465, net_monthly: 2465 },
        { household_size: 3, gross_monthly: 3107, net_monthly: 3107 },
        { household_size: 4, gross_monthly: 3749, net_monthly: 3749 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income at or below 150% FPL or 60% of state median income",
        "Households with elderly, disabled, or young children get priority",
        "Available for renters and homeowners",
        "Some programs also help with weatherization/insulation",
      ],
    },
    benefit: {
      type: "Energy bill payment assistance",
      average_amount: "$200-1,000 per heating season",
      duration: "Annual (reapply each year)",
    },
    application: {
      apply_url: "https://liheap.acf.hhs.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "2-4 weeks",
      expedited_available: true,
      expedited_timeline: "Emergency heating/cooling assistance available",
    },
    documents_needed: [
      "Photo ID",
      "Social Security numbers for household members",
      "Proof of income (last 30 days)",
      "Most recent utility bill",
      "Proof of residency",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find your state LIHEAP office",
        description: "Contact your state's LIHEAP office or community action agency.",
        time_estimate: "5 minutes",
        action_url: "https://liheap.acf.hhs.gov/",
        action_label: "Find My State Program →",
      },
      {
        step_number: 2,
        title: "Apply during the open enrollment period",
        description: "Most states accept applications in fall/winter for heating assistance.",
        time_estimate: "20-30 minutes",
      },
      {
        step_number: 3,
        title: "Receive assistance",
        description: "Payment is made directly to your utility company.",
        time_estimate: "2-4 weeks",
      },
    ],
    faqs: [
      { question: "Can renters apply?", answer: "Yes. If you pay heating/cooling costs (directly or through rent), you may qualify." },
      { question: "What if my heat is about to be shut off?", answer: "Contact your state LIHEAP office immediately. Emergency/crisis assistance may be available." },
    ],
    can_combine_with: ["snap", "medicaid", "section-8", "tanf"],
    source_url: "https://liheap.acf.hhs.gov/",
    last_updated: "2024-10",
  },

  {
    slug: "lifeline-phone",
    name: "Lifeline",
    full_name: "Lifeline Phone/Internet Assistance",
    category: "utilities",
    summary: "Discounted phone or internet service for low-income households",
    federal_or_state: "federal",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1823, net_monthly: 1823 },
        { household_size: 2, gross_monthly: 2465, net_monthly: 2465 },
        { household_size: 3, gross_monthly: 3107, net_monthly: 3107 },
        { household_size: 4, gross_monthly: 3749, net_monthly: 3749 },
      ],
      citizenship_required: false,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income at or below 135% FPL or participating in SNAP, Medicaid, SSI, FPHA, or veterans pension",
        "One Lifeline benefit per household",
        "Can be used for phone OR internet service (not both)",
      ],
    },
    benefit: {
      type: "Monthly discount on phone or internet",
      average_amount: "$9.25/month discount",
      duration: "Ongoing while eligible",
    },
    application: {
      apply_url: "https://www.lifelinesupport.org/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "1-2 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Proof of income or proof of participation in a qualifying program",
      "Photo ID",
    ],
    steps: [
      {
        step_number: 1,
        title: "Check eligibility",
        description: "Visit lifelinesupport.org to verify eligibility.",
        time_estimate: "5 minutes",
        action_url: "https://www.lifelinesupport.org/",
        action_label: "Check Eligibility →",
      },
      {
        step_number: 2,
        title: "Choose a provider",
        description: "Select a Lifeline provider in your area.",
        time_estimate: "10 minutes",
      },
      {
        step_number: 3,
        title: "Apply",
        description: "Submit your application through the National Verifier system.",
        time_estimate: "10-15 minutes",
      },
    ],
    faqs: [
      { question: "Can I get both phone and internet discounts?", answer: "You can apply the Lifeline benefit to either phone or internet service, but not both." },
    ],
    can_combine_with: ["snap", "medicaid", "acp-internet"],
    source_url: "https://www.lifelinesupport.org/",
    last_updated: "2024-10",
  },

  {
    slug: "acp-internet",
    name: "ACP",
    full_name: "Affordable Connectivity Program",
    category: "utilities",
    summary: "Discount on monthly internet service for low-income households",
    federal_or_state: "federal",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 2430, net_monthly: 2430 },
        { household_size: 2, gross_monthly: 3287, net_monthly: 3287 },
        { household_size: 3, gross_monthly: 4143, net_monthly: 4143 },
        { household_size: 4, gross_monthly: 5000, net_monthly: 5000 },
      ],
      citizenship_required: false,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income at or below 200% FPL",
        "Auto-qualify if receiving SNAP, Medicaid, WIC, SSI, or Pell Grant",
        "One benefit per household",
        "Note: ACP funding status may change — check for current availability",
      ],
    },
    benefit: {
      type: "Monthly internet discount",
      average_amount: "$30/month discount ($75 on Tribal lands)",
      duration: "Ongoing while funded and eligible",
    },
    application: {
      apply_url: "https://www.affordableconnectivity.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "1-2 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Proof of income or qualifying program participation",
      "Photo ID",
      "Social Security number (last 4 digits)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Apply at ACPBenefit.org",
        description: "Complete the online application with the Universal Service Administrative Company.",
        time_estimate: "10 minutes",
        action_url: "https://www.affordableconnectivity.gov/",
        action_label: "Apply Now →",
      },
      {
        step_number: 2,
        title: "Choose a provider",
        description: "Select a participating internet provider in your area and apply the discount.",
        time_estimate: "10 minutes",
      },
    ],
    faqs: [
      { question: "Is the ACP program still running?", answer: "ACP funding status may change. Check affordableconnectivity.gov for the latest information." },
    ],
    can_combine_with: ["snap", "lifeline-phone", "medicaid"],
    source_url: "https://www.affordableconnectivity.gov/",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // EDUCATION & TRAINING
  // ═══════════════════════════════════════════════════
  {
    slug: "pell-grant",
    name: "Pell Grant",
    full_name: "Federal Pell Grant",
    category: "education",
    summary: "Free money for college — does not need to be repaid — for low-income undergraduate students",
    federal_or_state: "federal",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 2500, net_monthly: 2500 },
        { household_size: 2, gross_monthly: 3000, net_monthly: 3000 },
        { household_size: 3, gross_monthly: 4000, net_monthly: 4000 },
        { household_size: 4, gross_monthly: 5000, net_monthly: 5000 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For undergraduate students who have not yet earned a bachelor's degree",
        "Based on financial need determined by FAFSA",
        "Maximum award: $7,395 for 2024-25",
        "Auto-qualify if adjusted gross income under $30,000 and family size meets threshold",
      ],
    },
    benefit: {
      type: "Grant (free money — no repayment)",
      average_amount: "Up to $7,395/year (2024-25)",
      duration: "Up to 6 years (12 semesters)",
    },
    application: {
      apply_url: "https://studentaid.gov/h/apply-for-aid/fafsa",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "3-5 days for FAFSA processing",
      expedited_available: false,
    },
    documents_needed: [
      "Social Security number",
      "Federal tax returns (or parents' if dependent)",
      "W-2 forms and records of income",
      "Bank statements",
      "FSA ID (create at studentaid.gov)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Create an FSA ID",
        description: "Go to studentaid.gov and create your FSA ID. Your parent/guardian also needs one if you're a dependent.",
        time_estimate: "10 minutes",
        action_url: "https://studentaid.gov/fsa-id/create-account/launch",
        action_label: "Create FSA ID →",
      },
      {
        step_number: 2,
        title: "Complete the FAFSA",
        description: "Fill out the Free Application for Federal Student Aid. It takes about 30-45 minutes.",
        time_estimate: "30-45 minutes",
        action_url: "https://studentaid.gov/h/apply-for-aid/fafsa",
        action_label: "Fill Out FAFSA →",
      },
      {
        step_number: 3,
        title: "Review your Student Aid Report",
        description: "You'll receive a Student Aid Report within days. Review it for accuracy.",
        time_estimate: "3-5 days",
      },
      {
        step_number: 4,
        title: "Receive your award letter",
        description: "Your school will send you an award letter showing your Pell Grant amount.",
        time_estimate: "Varies by school",
      },
    ],
    faqs: [
      { question: "Do I have to pay this back?", answer: "No! Pell Grants are free money. Unlike loans, they do not need to be repaid." },
      { question: "Can I use Pell Grants at community colleges?", answer: "Yes. Pell Grants can be used at any participating college or university, including community colleges and trade schools." },
    ],
    can_combine_with: ["snap", "medicaid", "wioa-job-training"],
    source_url: "https://studentaid.gov/understand-aid/types/grants/pell",
    last_updated: "2024-10",
  },

  {
    slug: "adult-education",
    name: "Adult Education",
    full_name: "Adult Education and Family Literacy (AEFLA)",
    category: "education",
    summary: "Free GED preparation, adult literacy, and English language classes",
    federal_or_state: "both",
    eligibility: {
      income_limits: [],
      citizenship_required: false,
      age_range: { min: 16 },
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For adults 16+ who are not enrolled in school",
        "No income requirement for most programs",
        "Includes GED/HSE prep, basic literacy, and English language learning",
        "Free in most states",
      ],
    },
    benefit: {
      type: "Free classes and education services",
      average_amount: "Free",
      duration: "Until goals are met",
    },
    application: {
      apply_url: "https://www2.ed.gov/about/offices/list/ovae/pi/AdultEd/index.html",
      can_apply_online: false,
      requires_interview: false,
      decision_timeline: "Immediate (class enrollment)",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID",
      "Proof of residency (varies by program)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Find a program near you",
        description: "Search for adult education programs at your local library, community college, or school district.",
        time_estimate: "10 minutes",
      },
      {
        step_number: 2,
        title: "Take a placement assessment",
        description: "Most programs require a brief skills assessment to place you in the right class level.",
        time_estimate: "1-2 hours",
      },
      {
        step_number: 3,
        title: "Enroll and start classes",
        description: "Sign up for classes and begin attending. Most programs offer flexible schedules including evenings.",
        time_estimate: "Ongoing",
      },
    ],
    faqs: [
      { question: "Do I need to be a US citizen?", answer: "No. Adult education programs are generally open to all residents regardless of immigration status." },
    ],
    can_combine_with: ["snap", "wioa-job-training", "pell-grant"],
    source_url: "https://www2.ed.gov/about/offices/list/ovae/pi/AdultEd/index.html",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // TRANSPORTATION
  // ═══════════════════════════════════════════════════
  {
    slug: "medicaid-transport",
    name: "Medicaid Transport",
    full_name: "Non-Emergency Medical Transportation (NEMT)",
    category: "transport",
    summary: "Free rides to medical appointments for Medicaid recipients",
    federal_or_state: "both",
    eligibility: {
      income_limits: [],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Must be enrolled in Medicaid",
        "For non-emergency medical appointments only",
        "Must not have other transportation available",
        "Includes rides to doctor visits, pharmacy, therapy, dialysis, etc.",
      ],
    },
    benefit: {
      type: "Free transportation to medical appointments",
      average_amount: "Free",
      duration: "Ongoing while on Medicaid",
    },
    application: {
      apply_url: "https://www.medicaid.gov/medicaid/benefits/nonemergency-medical-transportation/index.html",
      can_apply_online: false,
      requires_interview: false,
      decision_timeline: "Immediate if Medicaid-enrolled",
      expedited_available: false,
    },
    documents_needed: [
      "Medicaid ID card",
      "Appointment details (date, time, location)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Call your Medicaid plan",
        description: "Contact your Medicaid managed care plan or state Medicaid office to request transportation.",
        time_estimate: "5-10 minutes",
      },
      {
        step_number: 2,
        title: "Schedule your ride",
        description: "Request a ride at least 2-3 business days before your appointment.",
        time_estimate: "5 minutes",
      },
      {
        step_number: 3,
        title: "Ride to your appointment",
        description: "A van, taxi, or rideshare will pick you up and bring you home after your appointment.",
        time_estimate: "Varies",
      },
    ],
    faqs: [
      { question: "Can I use this for pharmacy trips?", answer: "Yes, NEMT covers transportation to pharmacies, therapy, and other Medicaid-covered services." },
    ],
    can_combine_with: ["medicaid"],
    source_url: "https://www.medicaid.gov/medicaid/benefits/nonemergency-medical-transportation/index.html",
    last_updated: "2024-10",
  },

  {
    slug: "reduced-fare-transit",
    name: "Reduced Fare Transit",
    full_name: "Reduced Fare Public Transit Programs",
    category: "transport",
    summary: "Discounted public bus and rail fares for seniors, people with disabilities, and low-income riders",
    federal_or_state: "both",
    eligibility: {
      income_limits: [],
      citizenship_required: false,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Federal law requires half-price fares for seniors (65+) and people with disabilities during off-peak hours",
        "Many cities offer additional discounts or free transit for low-income riders",
        "Check your local transit authority for specific programs",
      ],
    },
    benefit: {
      type: "Discounted public transportation",
      average_amount: "50% or more off regular fares",
      duration: "Ongoing",
    },
    application: {
      apply_url: "https://www.transit.dot.gov/",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "1-2 weeks",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID with date of birth (for senior discount)",
      "Disability documentation (for disability discount)",
      "Proof of income (for low-income programs)",
    ],
    steps: [
      {
        step_number: 1,
        title: "Contact your local transit authority",
        description: "Find your city's public transit system and ask about reduced fare programs.",
        time_estimate: "5-10 minutes",
      },
      {
        step_number: 2,
        title: "Apply for a reduced fare card",
        description: "Submit your application and documentation to receive a reduced fare transit card.",
        time_estimate: "15-20 minutes",
      },
    ],
    faqs: [
      { question: "Is this available everywhere?", answer: "All public transit systems that receive federal funding must offer reduced fares for seniors and people with disabilities. Low-income programs vary by city." },
    ],
    can_combine_with: ["medicaid", "snap"],
    source_url: "https://www.transit.dot.gov/",
    last_updated: "2024-10",
  },

  // ═══════════════════════════════════════════════════
  // Additional programs (referenced in categories)
  // ═══════════════════════════════════════════════════
  {
    slug: "medicare-savings",
    name: "Medicare Savings",
    full_name: "Medicare Savings Programs",
    category: "health",
    summary: "Help paying Medicare premiums, deductibles, and copays for low-income seniors and people with disabilities",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 1715, net_monthly: 1715 },
        { household_size: 2, gross_monthly: 2320, net_monthly: 2320 },
      ],
      citizenship_required: true,
      age_range: { min: 65 },
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "For Medicare beneficiaries with limited income",
        "Can save $170+/month on Medicare Part B premiums",
        "Also covers deductibles and copays in some programs",
        "Income limits vary by program level (QMB, SLMB, QI)",
      ],
    },
    benefit: {
      type: "Medicare cost assistance",
      average_amount: "$170+/month savings on premiums",
      duration: "Ongoing while eligible",
    },
    application: {
      apply_url: "https://www.medicare.gov/basics/costs/help/drug-costs",
      can_apply_online: true,
      requires_interview: false,
      decision_timeline: "30-45 days",
      expedited_available: false,
    },
    documents_needed: [
      "Medicare card",
      "Proof of income",
      "Photo ID",
    ],
    steps: [
      {
        step_number: 1,
        title: "Contact your State Health Insurance Assistance Program (SHIP)",
        description: "SHIP counselors can help you determine which Medicare Savings Program you qualify for.",
        time_estimate: "30 minutes",
        action_url: "https://www.shiphelp.org/",
        action_label: "Find SHIP Counselor →",
      },
      {
        step_number: 2,
        title: "Apply through your state Medicaid office",
        description: "Medicare Savings Programs are administered through your state Medicaid office.",
        time_estimate: "20-30 minutes",
      },
    ],
    faqs: [
      { question: "Can I have Medicare and Medicaid?", answer: "Yes. This is called 'dual eligibility' and you may qualify for extra help with costs." },
    ],
    can_combine_with: ["medicaid", "snap", "liheap"],
    source_url: "https://www.medicare.gov/basics/costs/help/drug-costs",
    last_updated: "2024-10",
  },

  {
    slug: "hud-housing",
    name: "HUD Public Housing",
    full_name: "HUD Public Housing Program",
    category: "housing",
    summary: "Affordable rental housing owned and managed by local public housing authorities",
    federal_or_state: "both",
    eligibility: {
      income_limits: [
        { household_size: 1, gross_monthly: 2083, net_monthly: 2083 },
        { household_size: 2, gross_monthly: 2383, net_monthly: 2383 },
        { household_size: 3, gross_monthly: 2679, net_monthly: 2679 },
        { household_size: 4, gross_monthly: 2975, net_monthly: 2975 },
      ],
      citizenship_required: true,
      requires_children: false,
      requires_disability: false,
      requires_employment_history: false,
      special_notes: [
        "Income generally must be below 80% of Area Median Income",
        "Rent is set at 30% of your adjusted income",
        "Waitlists can be very long",
        "Includes apartments, townhouses, and single-family homes",
      ],
    },
    benefit: {
      type: "Below-market rent housing",
      average_amount: "You pay 30% of your income as rent",
      duration: "Ongoing while eligible",
    },
    application: {
      apply_url: "https://www.hud.gov/topics/rental_assistance/phprog",
      can_apply_online: true,
      requires_interview: true,
      decision_timeline: "Varies (waitlists common)",
      expedited_available: false,
    },
    documents_needed: [
      "Photo ID for all adult household members",
      "Social Security cards",
      "Birth certificates",
      "Proof of income",
      "Previous landlord references",
    ],
    steps: [
      {
        step_number: 1,
        title: "Contact your local housing authority",
        description: "Find and contact your local PHA to inquire about availability and waitlists.",
        time_estimate: "15 minutes",
        action_url: "https://www.hud.gov/program_offices/public_indian_housing/pha/contacts",
        action_label: "Find My Housing Authority →",
      },
      {
        step_number: 2,
        title: "Submit your application",
        description: "Apply when the waitlist is open. Provide all required documentation.",
        time_estimate: "30-45 minutes",
      },
      {
        step_number: 3,
        title: "Wait for selection",
        description: "You'll be placed on the waitlist based on need and priority factors.",
        time_estimate: "Months to years",
      },
    ],
    faqs: [
      { question: "How much is rent?", answer: "Rent is generally set at 30% of your adjusted gross income, making it affordable regardless of income level." },
    ],
    can_combine_with: ["snap", "medicaid", "liheap", "tanf"],
    source_url: "https://www.hud.gov/topics/rental_assistance/phprog",
    last_updated: "2024-10",
  },
];

// Helper: get program by slug
export function getProgramBySlug(slug: string): Program | undefined {
  return programs.find((p) => p.slug === slug);
}

// Helper: get programs by category
export function getProgramsByCategory(category: string): Program[] {
  return programs.filter((p) => p.category === category);
}

// Helper: get all unique categories with program counts
export function getCategoriesWithCounts(): { category: string; count: number }[] {
  const counts: Record<string, number> = {};
  for (const p of programs) {
    counts[p.category] = (counts[p.category] || 0) + 1;
  }
  return Object.entries(counts).map(([category, count]) => ({ category, count }));
}
